issue13 add task is finished
kiarash2077/To-Do-List-Application pull request #19
Opened 2024-10-15 22:47 UTC by Hailey-cloud

2024-10-15 22:59 UTC, shigeokitamura commented on to_do_list_part_two.py
> +    deadline = input("Enter the dead line(YYYY-MM-DD): ")
In this line, deadline is str type.
We should discuss about the date type of the deadline: just leave it in str type or convert to datetime type

2024-10-15 22:59 UTC, shigeokitamura commented on to_do_list_part_two.py
> +    priority = input("Enter the priority(high, medium, low): ")
You can check whether priority is `high` or `medium` or `low` here.

In line 7, you only check whether priority is empty or not.

2024-10-15 23:16 UTC, shigeokitamura commented on to_do_list_part_two.py
> +    deadline = input("Enter the dead line(YYYY-MM-DD): ")
We decided to keep deadline as str type.
no need to change.

2024-10-15 23:34 UTC, shigeokitamura requested changes

2024-10-15 23:34 UTC, shigeokitamura commented on .idea/To-Do-List-Application.iml
Can you delete this file from your commit?
This file is not needed for the repository.

2024-10-15 23:38 UTC, shigeokitamura approved these changes

2024-10-15 23:50 UTC, shigeokitamura commented on to_do_list_part_two.py
> +    deadline = input("Enter the dead line(YYYY-MM-DD): ")
Can you handle invalid inputs?
Such as entering an incorrect date format like `2024/10/15`

2024-10-16 22:52 UTC, kiarash2077 approved these changes

2024-10-16 22:53 UTC, merged